"""initial revision.

Revision ID: 55d759c7dcba
Revises:
Create Date: 2022-11-14 15:42:26.715662
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "55d759c7dcba"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("dob", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_author")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("author")
    # ### end Alembic commands ###
