"""add books domain.

Revision ID: c7bd3f5d6e72
Revises: 55d759c7dcba
Create Date: 2022-11-19 14:16:21.394270
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c7bd3f5d6e72"
down_revision = "55d759c7dcba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["author.id"], name=op.f("fk_book_author_id_author")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book")
    # ### end Alembic commands ###
